openapi: 3.1.0
info:
  title: API для проекта «HNY AMEDIATEKA (механика)»
  description: FHNY AMEDIATEKA — это.
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

tags:
  - name: users
    description: Действия с пользователем
  - name: game
    description: Действия с игрой

paths:
  /users/login:
    post:
      tags:
        - users
      summary: Вход в закрытую часть приложения
      description: Авторизовывает пользователя.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginRequest'
      responses:
        '200':
          description: Успешная аутентификация. Возвращается информация о пользователе.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loggedUserRdo'
        '400':
          description: Ошибка запроса. Некорректные данные при аутентификации.
        '401':
          description: Ошибка аутентификации. Неверный пароль.

  /game/skip:
    post:
      tags:
        - game
      summary: Пропуск игры
      description: Пропускает игру и выдает первый подарок.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginRequest'
      responses:
        '200':
          description: Успешный пропуск игры. Выдает первый подарок или сообщение о том что подарок уже был выдан или все подарки были выданы.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gameRdo'
        '400':
          description: Ошибка запроса. Некорректные данные для пропуска игры.
        '401':
          description: Ошибка аутентификации.

  /game/play-riddle:
    post:
      tags:
        - game
      summary: Выдача подарка
      description: Выдает подарок.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginRequest'
      responses:
        '200':
          description: Успешная выдача подарка. Выдает выдает подарок или сообщение о том что подарки уже были выданы.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/gameRdo'
        '400':
          description: Ошибка запроса. Некорректные данные для выдачи подарка.
        '401':
          description: Ошибка аутентификации.

components:
  schemas:

    user:
      type: object
      properties:
        password:
          type: string
          description: Пароль пользователя.
        hasPlayed:
          type: boolean
          description: Логическое значение, указывающее, участвовал ли пользователь в игре или нет.
        giftsReceived:
          type: number
          description: Количество подарков, полученных пользователем.
        createdAt:
          type: string
          format: date
          description: Метка времени, указывающая дату и время создания учетной записи пользователя.

    loginRequest:
      type: object
      properties:
        password:
          type: string
          minLength: 6
          maxLength: 12

    loggedUserRdo:
      type: object
      properties:
        id:
          type: string
        password:
          type: string
        hasPlayed:
          type: boolean
        giftsReceived:
          type: number
          format: date
        createdAt:
          type: string
          format: date

    gameRdo:
      type: object
      properties:
        message:
          type: string
        promoCode:
          type: string
